version: '3.7'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5433:5432  # (local mashinin portu) : (docker in icindeki servisin portu)
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: